/* PROD-EX Duel - card set (original, no third-party IP). Theme: arcane academy.
   Resource = "Appunto di Studio" (generated by real Pomodoros, labeled with the task).
   Pure data. */
(function (root) {
  "use strict";
  // kind: creature | spell
  // keywords (creatures): slancio (no summon sickness), difensore (taunt)
  // spell effect resolved by duel-core. upkeep: {type:"mana"|"draw", amount}
  var CARDS = {
    scintilla:   { name: "Favilla Nominata", kind: "creature", cost: 1, power: 1, tough: 1, kw: ["slancio"],
                   art: "spark", type: "Spirito - Novizio", text: "Slancio. Quando entra: 1 danno al nemico.",
                   enter: { type: "damage_enemy", amount: 1 } },
    sentinella:  { name: "Sentinella della Soglia", kind: "creature", cost: 2, power: 0, tough: 4, kw: ["difensore"],
                   art: "sentinel", type: "Spirito - Guardia", text: "Difensore: va bloccato per primo." },
    messaggero:  { name: "Studente Diligente", kind: "creature", cost: 2, power: 2, tough: 1, kw: [],
                   art: "runner", type: "Spirito - Allievo", text: "Quando entra: pesca una carta.",
                   enter: { type: "draw", amount: 1 } },
    guardiano:   { name: "Custode dell'Archivio", kind: "creature", cost: 3, power: 2, tough: 3, kw: [],
                   art: "guardian", type: "Spirito - Custode", text: "All'inizio del turno: +1 Appunto disponibile.",
                   upkeep: { type: "mana", amount: 1 } },
    operaio:     { name: "Famiglio Operoso", kind: "creature", cost: 3, power: 3, tough: 3, kw: [],
                   art: "worker", type: "Famiglio", text: "" },
    colosso:     { name: "Golem d'Inchiostro", kind: "creature", cost: 5, power: 5, tough: 6, kw: [],
                   art: "colossus", type: "Costrutto", text: "" },
    furia:       { name: "Lampo di Genio", kind: "creature", cost: 4, power: 4, tough: 2, kw: ["slancio"],
                   art: "fury", type: "Spirito - Ispirazione", text: "Slancio." },
    rigenerante: { name: "Spirito Curativo", kind: "creature", cost: 4, power: 2, tough: 4, kw: [],
                   art: "healer", type: "Spirito - Linfa", text: "Quando entra: +4 Vigore.",
                   enter: { type: "heal", amount: 4 } },

    pomodoro:    { name: "Saetta Mentale", kind: "spell", cost: 1, art: "tomato", type: "Arte Arcana",
                   text: "2 danni a una creatura o al nemico.", effect: { type: "damage_any", amount: 2 } },
    flow:        { name: "Stato di Grazia", kind: "spell", cost: 3, art: "wave", type: "Arte Arcana",
                   text: "4 danni al nemico.", effect: { type: "damage_enemy", amount: 4 } },
    time_block:  { name: "Ward Protettivo", kind: "spell", cost: 2, art: "clock", type: "Arte Arcana",
                   text: "Una tua creatura: +0/+3 e cura il danno.", effect: { type: "buff_heal", power: 0, tough: 3 } },
    delegate:    { name: "Bando", kind: "spell", cost: 2, art: "arrow", type: "Arte Arcana",
                   text: "Distruggi una creatura nemica con costituzione 3 o meno.", effect: { type: "destroy", maxTough: 3 } },
    eisenhower:  { name: "Lettura Veloce", kind: "spell", cost: 1, art: "grid", type: "Arte Arcana",
                   text: "Pesca 2 carte.", effect: { type: "draw", amount: 2 } },
    recovery:    { name: "Pozione Ristoratrice", kind: "spell", cost: 1, art: "leaf", type: "Arte Arcana",
                   text: "+6 Vigore.", effect: { type: "heal", amount: 6 } },
    caffeina:    { name: "Tonico Arcano", kind: "spell", cost: 0, art: "mug", type: "Arte Arcana",
                   text: "+2 Appunti disponibili questo turno.", effect: { type: "mana", amount: 2 } },
    secondo:     { name: "Eco Arcana", kind: "spell", cost: 2, art: "refresh", type: "Arte Arcana",
                   text: "Una tua creatura: stappa e puo' riattaccare.", effect: { type: "untap" } },

    // ---- unlockable cards (meta-collection, by level) ----
    fulmine:     { name: "Fulmine Arcano", kind: "spell", cost: 2, art: "spark", type: "Arte Arcana",
                   text: "3 danni a una creatura o al nemico.", effect: { type: "damage_any", amount: 3 } },
    mentore:     { name: "Mentore dell'Arcano", kind: "creature", cost: 3, power: 1, tough: 3, kw: [],
                   art: "runner", type: "Spirito - Maestro", text: "All'inizio del turno: pesca una carta.",
                   upkeep: { type: "draw", amount: 1 } },
    baluardo:    { name: "Baluardo Arcano", kind: "creature", cost: 4, power: 0, tough: 7, kw: ["difensore"],
                   art: "sentinel", type: "Spirito - Guardia", text: "Difensore: muro quasi invalicabile." },
    titano:      { name: "Titano d'Inchiostro", kind: "creature", cost: 6, power: 7, tough: 7, kw: [],
                   art: "colossus", type: "Costrutto - Titano", text: "" }
  };

  // starting deck: creatures + arts (opening hand is 5 creatures)
  var STARTER_DECK = [
    "scintilla", "scintilla", "scintilla", "messaggero", "messaggero", "sentinella",
    "operaio", "operaio", "guardiano", "furia", "colosso", "rigenerante",
    "pomodoro", "pomodoro", "flow", "time_block", "delegate", "eisenhower", "recovery", "caffeina", "secondo"
  ];

  var REWARD_POOL = ["colosso", "furia", "flow", "delegate", "rigenerante", "guardiano", "secondo", "time_block", "operaio"];

  // boss gauntlet: faced one after another, escalating. duel-core scales beyond the list.
  var BOSSES = [
    { name: "Compito in Classe", hp: 18,
      intents: [ { type: "attack", amount: 3, label: "Attacca 3" }, { type: "summon", card: "ombra", label: "Evoca Ombra" }, { type: "attack", amount: 4, label: "Attacca 4" } ] },
    { name: "La Sessione d'Esami", hp: 26,
      intents: [ { type: "buff", amount: 1, label: "Si rafforza +1" }, { type: "attack", amount: 4, label: "Attacca 4" }, { type: "attack", amount: 6, label: "Attacca 6" } ] },
    { name: "Il Demone della Procrastinazione", hp: 34,
      intents: [ { type: "attack", amount: 5, label: "Attacca 5" }, { type: "summon", card: "ombra", label: "Evoca Ombra" }, { type: "attack", amount: 7, label: "Attacca 7" }, { type: "buff", amount: 1, label: "Si rafforza +1" } ] },
    { name: "La Scadenza", hp: 44,
      intents: [ { type: "attack", amount: 6, label: "Attacca 6" }, { type: "buff", amount: 2, label: "Cresce +2" }, { type: "attack", amount: 8, label: "Attacca 8" }, { type: "summon", card: "ombra", label: "Evoca Ombra" }, { type: "attack", amount: 10, label: "Colpo Finale 10" } ] }
  ];
  var ENEMY_CREATURES = {
    ombra: { name: "Ombra del Dubbio", power: 2, tough: 2, art: "shadow", type: "Distrazione" }
  };

  // Appunto value by Pomodoro duration (minutes)
  var APPUNTO_VALUE = { 5: 1, 10: 2, 15: 4, 25: 6 };

  // meta-collection: cards unlocked by planeswalker level (shared progression)
  var UNLOCKS = [
    { level: 2, card: "fulmine" }, { level: 3, card: "mentore" },
    { level: 4, card: "baluardo" }, { level: 5, card: "titano" }
  ];
  function unlockedCards(level) { return UNLOCKS.filter(function (u) { return (level || 1) >= u.level; }).map(function (u) { return u.card; }); }

  // Rituali (passive run bonuses), unlocked by level
  var RITUALS = [
    { id: "mattiniero", name: "Mattiniero", desc: "+1 Appunto disponibile a ogni turno", unlock: 1 },
    { id: "tempra", name: "Tempra", desc: "+8 Vigore massimo", unlock: 2 },
    { id: "lettore", name: "Lettore Vorace", desc: "Pesca +1 carta a ogni turno", unlock: 3 }
  ];
  function unlockedRituals(level) { return RITUALS.filter(function (r) { return (level || 1) >= r.unlock; }); }
  function ritualById(id) { return RITUALS.find(function (r) { return r.id === id; }) || null; }

  var API = {
    CARDS: CARDS, STARTER_DECK: STARTER_DECK, REWARD_POOL: REWARD_POOL,
    BOSSES: BOSSES, ENEMY_CREATURES: ENEMY_CREATURES, APPUNTO_VALUE: APPUNTO_VALUE,
    UNLOCKS: UNLOCKS, unlockedCards: unlockedCards, RITUALS: RITUALS,
    unlockedRituals: unlockedRituals, ritualById: ritualById
  };
  if (typeof module !== "undefined" && module.exports) module.exports = API;
  root.PRODEX_CARDS = API;
})(typeof window !== "undefined" ? window : globalThis);
